---
name: Build Docker Image

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Show var
        run: |
          echo IMAGE_NAME=${{ env.IMAGE_NAME }}
          echo IMAGE_RNAME=$IMAGE_RNAME
          echo TAG_NAMES=$TAG_NAMES
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/birdsitelive:latest
